import { EliteMark, Pill, SectionTitle, SuccessLine } from "@/components/enem/Brand";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { ArrowRight, BookOpen, BrainCircuit, CalendarDays, CheckCircle2, ChevronRight, CircleHelp, Clock3, Compass, ExternalLink, FileText, GraduationCap, LineChart, Menu, PenLine, Search, ShieldCheck, Sparkles, Target, X } from "lucide-react";
import { useState } from "react";

type MarketingKind = "home" | "sobre" | "metodologia" | "disciplinas" | "biblioteca" | "planos" | "login" | "cadastro" | "recuperar" | "redefinir";

const navigation = [
  ["Metodologia", "/metodologia"], ["Disciplinas", "/disciplinas"], ["Biblioteca", "/biblioteca"], ["Sobre", "/sobre"],
] as const;

function PublicHeader() {
  const [open, setOpen] = useState(false);
  return <header className="public-header"><a href="/" className="shrink-0"><EliteMark /></a><nav className="hidden items-center gap-7 lg:flex">{navigation.map(([label, href]) => <a key={href} href={href} className="public-nav-link">{label}</a>)}</nav><div className="hidden items-center gap-3 lg:flex"><a href="/login" className="btn-ghost">Entrar</a><a href="/cadastro" className="btn-primary btn-small">Começar a estudar <ArrowRight /></a></div><button className="icon-button lg:hidden" aria-label="Abrir menu" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button>{open ? <div className="public-mobile-menu">{navigation.map(([label, href]) => <a key={href} href={href}>{label}</a>)}<a href="/login">Entrar</a><a href="/cadastro" className="btn-primary">Começar a estudar</a></div> : null}</header>;
}

function PublicFooter() {
  return <footer className="public-footer"><div className="footer-grid"><div><EliteMark /><p className="mt-5 max-w-sm text-sm leading-6 text-slate-500">Preparação organizada para quem quer estudar com método, acompanhar o progresso e tomar decisões melhores a cada dia.</p></div><div><p className="footer-label">Explorar</p><a href="/metodologia">Metodologia</a><a href="/disciplinas">Disciplinas</a><a href="/biblioteca">Biblioteca</a></div><div><p className="footer-label">Informações</p><a href="/privacidade">Privacidade</a><a href="/termos">Termos de uso</a><a href="https://www.gov.br/inep/pt-br/areas-de-atuacao/avaliacao-e-exames-educacionais/enem" target="_blank" rel="noreferrer">Portal do Inep <ExternalLink className="inline h-3 w-3" /></a></div></div><div className="mt-12 border-t border-white/8 pt-6 text-xs text-slate-600">ENEM ELITE · Conteúdos demonstrativos autorais e referências registradas. Não há promessa de aprovação ou nota.</div></footer>;
}

function SearchBox() {
  const [query, setQuery] = useState("");
  const search = trpc.catalog.search.useQuery({ query }, { enabled: query.trim().length >= 2 });
  const total = (search.data?.contents.length ?? 0) + (search.data?.questions.length ?? 0) + (search.data?.videos.length ?? 0) + (search.data?.themes.length ?? 0);
  return <div className="search-box"><Search className="h-5 w-5 text-cyan-300" /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Busque um tema, conceito ou material" aria-label="Buscar no ENEM ELITE" />{query.trim().length >= 2 ? <div className="search-results">{search.isFetching ? <p>Buscando no catálogo...</p> : total ? <><p className="search-result-label">Resultados agrupados</p>{search.data?.contents.slice(0, 2).map((item: any) => <a href="/biblioteca" key={`c-${item.content.id}`}><BookOpen />{item.content.title}<span>{item.discipline.name}</span></a>)}{search.data?.questions.slice(0, 2).map((item: any) => <a href="/app/questoes" key={`q-${item.question.id}`}><Target />Questão: {item.question.stem.slice(0, 58)}…<span>{item.discipline.name}</span></a>)}{search.data?.videos.slice(0, 2).map((item: any) => <a href="/biblioteca" key={`v-${item.video.id}`}><CircleHelp />{item.video.title}<span>Vídeo · {item.discipline.name}</span></a>)}</> : <p>Nenhum resultado encontrado. Tente outro termo ou navegue pelas disciplinas.</p>}</div> : null}</div>;
}

function Home() {
  const catalog = trpc.catalog.bootstrap.useQuery();
  return <>
    <section className="hero-section"><div className="hero-orbit orbit-one" /><div className="hero-orbit orbit-two" /><div className="hero-grid" /><div className="hero-content"><div className="hero-copy"><Pill tone="cyan"><Sparkles className="h-3.5 w-3.5" /> Preparação intensiva, sem improviso</Pill><h1>Estude o ENEM com uma <span>rota que faz sentido.</span></h1><p>Plano adaptável de 31 dias, prática comentada e decisões guiadas pelo seu próprio histórico — não por promessas vazias.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><button className="btn-primary btn-large" onClick={() => startLogin()}>Montar minha rota <ArrowRight /></button><a href="/metodologia" className="btn-secondary btn-large">Conhecer a metodologia</a></div><div className="mt-9 grid grid-cols-1 gap-3 sm:grid-cols-3"><SuccessLine>Plano ajustável ao seu tempo</SuccessLine><SuccessLine>Questões autorais comentadas</SuccessLine><SuccessLine>Dados privados por estudante</SuccessLine></div></div><div className="hero-mission-card"><div className="mission-card-top"><span>ROTA DE HOJE</span><Pill tone="green">Em construção</Pill></div><div className="mission-ring"><div><strong>31</strong><span>dias de foco</span></div></div><div className="mission-line"><i /><span>Diagnóstico</span><b /><span>Consolidação</span><b /><span>Prática</span></div><div className="mission-task"><div className="task-icon"><BrainCircuit /></div><div><p>Recuperação ativa</p><span>Comece pelo diagnóstico para gerar sua rota.</span></div><ChevronRight /></div></div></div><div className="hero-search-wrap"><SearchBox /></div></section>

    <section className="public-section section-dark"><SectionTitle eyebrow="O que torna o estudo executável" title="Menos abas. Mais clareza sobre o próximo passo." description="Cada módulo está conectado ao banco de dados da sua conta. Quando você responde, conclui ou revisa, o painel passa a refletir o que de fato aconteceu." /><div className="feature-rail mt-10"><Feature icon={<CalendarDays />} title="Rota de 31 dias" text="Defina início, tempo disponível e dias de estudo. A agenda preserva tarefas concluídas ao recalcular o caminho." /><Feature icon={<Target />} title="Questões que ensinam" text="Responda, veja a explicação e transforme erros em revisões programadas." /><Feature icon={<PenLine />} title="Redação em processo" text="Escreva, salve versões, acompanhe palavras e use um checklist de treino." /><Feature icon={<LineChart />} title="Evolução sem inventar dados" text="Indicadores aparecem a partir do seu histórico; antes disso, você recebe orientação para começar." /></div></section>

    <section className="public-section"><div className="split-section"><div><p className="eyebrow">Método que respeita seu ritmo</p><h2 className="section-title">Da primeira dúvida ao pós-simulado, uma sequência de estudo.</h2><p className="mt-5 leading-7 text-slate-400">A plataforma estrutura diagnóstico, consolidação, prática, revisão, simulados e preparação final. O calendário da edição é configurável pela administração e guarda os dois dias de prova separadamente.</p><a href="/metodologia" className="inline-link mt-6">Ver como a rota é organizada <ArrowRight /></a></div><div className="phase-list"><Phase number="01" title="Diagnóstico" text="Identifique ponto de partida e matérias prioritárias." /><Phase number="02" title="Construção" text="Estude conceitos e exemplos antes de ampliar a prática." /><Phase number="03" title="Recuperação" text="Reveja erros em intervalos ajustáveis e possíveis." /><Phase number="04" title="Aplicação" text="Use simulados autorais para observar estratégia e tempo." /></div></div></section>

    <section className="public-section section-dark"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><SectionTitle eyebrow="Biblioteca demonstrativa" title="Material identificado, fonte registrada." description="O catálogo diferencia conteúdo autoral, fonte externa, material oficial e material gerado por IA. A demonstração começa com explicações completas, não títulos vazios." /><a href="/biblioteca" className="btn-secondary">Abrir biblioteca <ArrowRight /></a></div><div className="mt-10 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{catalog.isLoading ? Array.from({ length: 4 }).map((_, index) => <div className="content-card skeleton-card" key={index} />) : catalog.data?.contents.slice(0, 4).map((item: any) => <article className="content-card" key={item.content.id}><div className="flex items-center justify-between"><Pill tone="violet">{item.discipline.name}</Pill><span className="text-xs text-slate-500"><Clock3 className="mr-1 inline h-3.5 w-3.5" />{item.content.estimatedMinutes} min</span></div><h3>{item.content.title}</h3><p>{item.content.excerpt}</p><div className="content-card-footer"><span>{item.content.origin === "authorial" ? "Autoral" : item.content.origin}</span><a href="/biblioteca" aria-label={`Ler ${item.content.title}`}><ArrowRight /></a></div></article>)}</div></section>

    <section className="public-section"><div className="cta-band"><div><Pill tone="cyan">Comece com uma decisão simples</Pill><h2>Escolha sua data de início. A rota se organiza a partir dela.</h2><p>Sem cronograma impossível e sem uma contagem fictícia de alunos. Só um ambiente de estudo preparado para acompanhar o seu processo.</p></div><button className="btn-primary btn-large" onClick={() => startLogin()}>Criar minha rota <ArrowRight /></button></div></section>
  </>;
}

function Feature({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <article className="feature-card"><span className="feature-icon">{icon}</span><h3>{title}</h3><p>{text}</p></article>; }
function Phase({ number, title, text }: { number: string; title: string; text: string }) { return <div className="phase-item"><span>{number}</span><div><h3>{title}</h3><p>{text}</p></div></div>; }

function InformationPage({ kind }: { kind: Exclude<MarketingKind, "home" | "biblioteca" | "login" | "cadastro" | "recuperar" | "redefinir"> }) {
  const detail = {
    sobre: { eyebrow: "Sobre a plataforma", title: "Preparação organizada para quem quer assumir o controle do processo.", text: "ENEM ELITE é uma plataforma educacional que conecta plano de estudos, prática, revisão e registro de aprendizagem. Ela foi desenhada para estudantes do ensino médio e candidatos ao ENEM que preferem clareza a promessas de desempenho.", cards: [["Tecnologia a serviço do estudo", "O painel só usa dados registrados na conta do estudante."], ["Conteúdo com origem identificada", "Materiais autorais, oficiais, externos e assistidos por IA nunca são apresentados como a mesma coisa."], ["Privacidade por padrão", "Dados de estudo privados são consultados pelo próprio estudante ou por administração autorizada."]] },
    metodologia: { eyebrow: "Metodologia", title: "Uma sequência curta, adaptável e construída para caber na vida real.", text: "A rota de 31 dias começa pelo diagnóstico e combina consolidação, prática, revisão espaçada, simulados e preparação final. O estudante informa disponibilidade e matérias difíceis; o sistema organiza tarefas futuras e preserva o que já foi concluído.", cards: [["Diagnóstico", "Estabelece um ponto de partida antes de sugerir intensidade."], ["Recuperação ativa", "Erros e dúvidas voltam ao plano em intervalos configuráveis."], ["Pós-simulado", "O resultado aponta acertos e oportunidades de revisão; não simula TRI." ]] },
    disciplinas: { eyebrow: "Áreas de conhecimento", title: "Cinco frentes, uma rota conectada.", text: "A organização parte das áreas do ENEM: Linguagens, Redação, Ciências Humanas, Ciências da Natureza e Matemática. Os temas e habilidades podem ser editados pela administração conforme a Matriz de Referência e curadoria editorial.", cards: [["Linguagens", "Leitura, língua portuguesa, literatura, artes e comunicação."], ["Redação", "Projeto de texto, argumentação e intervenção responsável."], ["Humanas, Natureza e Matemática", "Investigação, análise de fontes, modelagem e resolução de situações-problema."]] },
    planos: { eyebrow: "Planos", title: "A plataforma está pronta para evoluir, não para cobrar sem infraestrutura real.", text: "Não existe checkout, assinatura ou monetização ativa nesta versão. Por isso, nenhum preço é apresentado como oferta. Quando houver uma integração de pagamento configurada, a página poderá informar condições reais de acesso.", cards: [["Acesso atual", "Sem cobrança configurada neste ambiente."], ["Transparência", "Funcionalidades e integrações são identificadas pelo estado real do produto."], ["Próximo passo", "Crie sua conta e organize uma rota de demonstração."]] },
  }[kind];
  return <section className="public-section info-page"><p className="eyebrow">{detail.eyebrow}</p><h1 className="page-title">{detail.title}</h1><p className="page-lead">{detail.text}</p><div className="info-grid">{detail.cards.map(card => <article key={card[0]} className="surface-panel"><CheckCircle2 className="h-5 w-5 text-cyan-300" /><h3>{card[0]}</h3><p>{card[1]}</p></article>)}</div></section>;
}

function Library() {
  const catalog = trpc.catalog.bootstrap.useQuery();
  return <section className="public-section library-page"><p className="eyebrow">Biblioteca pública de demonstração</p><h1 className="page-title">Conteúdo para estudar com contexto.</h1><p className="page-lead">Os materiais abaixo são demonstrativos, identificados por origem e acompanhados de referência. Links de vídeos aguardam rechecagem editorial antes de entrarem em recomendações automáticas.</p><SearchBox /><div className="mt-12 grid gap-6 lg:grid-cols-[.8fr_1.4fr]"><aside className="library-filter"><p className="footer-label">Áreas disponíveis</p>{catalog.data?.disciplines.map((discipline: any) => <a href={`#${discipline.slug}`} key={discipline.id}><span style={{ background: discipline.color }} />{discipline.name}</a>)}</aside><div className="space-y-5">{catalog.data?.contents.map((item: any) => <article className="library-item" id={item.discipline.slug} key={item.content.id}><div><Pill tone="cyan">{item.discipline.name}</Pill><h2>{item.content.title}</h2><p>{item.content.excerpt}</p><div className="mt-4 flex flex-wrap gap-2">{item.content.objectives.map((objective: string) => <span className="mini-tag" key={objective}>{objective}</span>)}</div></div><div className="library-meta"><span>{item.content.estimatedMinutes} min</span><span>{item.content.difficulty === "basic" ? "Base" : item.content.difficulty}</span><span>Origem: {item.content.origin === "authorial" ? "autoral" : item.content.origin}</span>{item.content.references[0] ? <a target="_blank" rel="noreferrer" href={item.content.references[0].url}>Referência <ExternalLink /></a> : null}</div></article>)}</div></div><div className="mt-12"><SectionTitle eyebrow="Vídeos públicos" title="Catálogo com status de disponibilidade" description="A plataforma não redistribui material de terceiros; cada item aponta para sua fonte. Os registros abaixo foram cadastrados como pendentes até uma rechecagem editorial de disponibilidade." /><div className="mt-6 grid gap-4 md:grid-cols-2">{catalog.data?.videos.map((item: any) => <article className="video-card" key={item.video.id}><div className="video-symbol"><CircleHelp /></div><div><Pill tone="amber">Pendente de rechecagem</Pill><h3>{item.video.title}</h3><p>{item.video.description}</p><a href={item.video.url} target="_blank" rel="noreferrer">Abrir na fonte <ExternalLink /></a></div></article>)}</div></div></section>;
}

function AuthPage({ mode }: { mode: "login" | "cadastro" | "recuperar" | "redefinir" }) {
  const copy = {
    login: ["Acesse sua rota de estudos.", "Entre com a conta segura disponível neste ambiente para abrir seu painel e manter o histórico no banco."],
    cadastro: ["Crie seu acesso de forma segura.", "O ENEM ELITE usa o provedor de identidade configurado no ambiente. Ao continuar, você poderá criar ou selecionar sua conta pelo fluxo oficial."],
    recuperar: ["Recuperação de acesso.", "Esta instalação não mantém senhas locais nem envia e-mails próprios. Use a recuperação da conta no provedor de identidade que você escolheu para entrar."],
    redefinir: ["Redefinição de acesso.", "Por segurança, a redefinição acontece no provedor de identidade. Volte ao login e siga as opções apresentadas pelo serviço."],
  }[mode];
  return <section className="auth-page"><div className="auth-grid"><div className="auth-brand"><EliteMark /><Pill tone="cyan">Identidade com sessão segura</Pill><h1>Seu estudo merece um espaço que não perde o fio.</h1><p>Histórico, plano e respostas ficam vinculados à sua conta autenticada. A plataforma não simula credenciais no navegador.</p></div><div className="surface-panel auth-card"><p className="eyebrow">{mode === "login" ? "Entrar" : mode === "cadastro" ? "Cadastro" : "Acesso"}</p><h2>{copy[0]}</h2><p>{copy[1]}</p><button className="btn-primary mt-7 w-full" onClick={() => startLogin()}>{mode === "cadastro" ? "Continuar para criar conta" : "Continuar com conta Manus"}<ArrowRight /></button>{mode === "login" ? <a href="/recuperar-senha">Não consegue entrar?</a> : null}{mode !== "login" ? <a href="/login">Voltar ao login</a> : null}</div></div></section>;
}

export default function Marketing({ kind = "home" }: { kind?: MarketingKind }) {
  return <div className="public-page"><PublicHeader /><main>{kind === "home" ? <Home /> : kind === "biblioteca" ? <Library /> : kind === "login" || kind === "cadastro" || kind === "recuperar" || kind === "redefinir" ? <AuthPage mode={kind} /> : <InformationPage kind={kind} />}</main><PublicFooter /></div>;
}
